version: "3.4"

services:
  web-app:
    image: feedback-nexjs
    build:
      context: .
      target: base
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:3000
    environment:
      REACT_APP_BACKEND_API_BASE: http://localhost:7002
